# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      disk:
      load:
      memory:
      network:
      processes:

exporters:
  debug:
  datadog/exporter:
    hostname: inspectit
    api:
      site: datadoghq.eu
      key: ${env:DD_API_KEY}

connectors:
  datadog/connector:

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, datadog/connector]
      processors: [batch]
      exporters: [debug, datadog/exporter]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, datadog/exporter, datadog/connector]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, datadog/exporter]
